from hearthy.exceptions import CardNotFound

_cards = [
    ('CS2_236',         'Divine Spirit'),
    ('CS2_142',         'Kobold Geomancer'),
    ('XXX_025',         'Do Nothing'),
    ('CS2_168',         'Murloc Raider'),
    ('CS2_103e',        'Charge'),
    ('GAME_006',        'NOOOOOOOOOOOO'),
    ('Mekka4t',         'Chicken'),
    ('CS2_mirror',      'Mirror Image'),
    ('EX1_302',         'Mortal Coil'),
    ('EX1_610',         'Explosive Trap'),
    ('EX1_274',         'Ethereal Arcanist'),
    ('XXX_004',         'Restore 5'),
    ('EX1_399e',        'Berserking'),
    ('CS2_162',         'Lord of the Arena'),
    ('CS2_032',         'Flamestrike'),
    ('CS2_064',         'Dread Infernal'),
    ('EX1_554t',        'Snake'),
    ('Mekka4',          'Poultryizer'),
    ('CS2_147',         'Gnomish Inventor'),
    ('EX1_308',         'Soulfire'),
    ('EX1_016',         'Sylvanas Windrunner'),
    ('EX1_295',         'Ice Block'),
    ('CS2_221',         'Spiteful Smith'),
    ('NEW1_012o',       'Mana Gorged'),
    ('NEW1_020',        'Wild Pyromancer'),
    ('EX1_055',         'Mana Addict'),
    ('EX1_549o',        'Bestial Wrath'),
    ('EX1_154',         'Wrath'),
    ('EX1_557',         'Nat Pagle'),
    ('NEW1_017',        'Hungry Crab'),
    ('EX1_145',         'Preparation'),
    ('NEW1_033o',       'Eye In The Sky'),
    ('CS1_113',         'Mind Control'),
    ('DREAM_04',        'Dream'),
    ('EX1_611',         'Freezing Trap'),
    ('CS2_059o',        'Blood Pact'),
    ('EX1_559',         'Archmage Antonidas'),
    ('EX1_085',         'Mind Control Tech'),
    ('XXX_013',         'Discard'),
    ('EX1_132',         'Eye for an Eye'),
    ('CS2_151',         'Silver Hand Knight'),
    ('ds1_whelptoken',  'Whelp'),
    ('EX1_411',         'Gorehowl'),
    ('NEW1_038o',       'Growth'),
    ('EX1_405',         'Shieldbearer'),
    ('EX1_575',         'Mana Tide Totem'),
    ('PlaceholderCard', 'Placeholder Card'),
    ('EX1_508o',        'Mlarggragllabl!'),
    ('EX1_507e',        'Mrgglaargl!'),
    ('EX1_309',         'Siphon Soul'),
    ('EX1_158',         'Soul of the Forest'),
    ('EX1_019',         'Shattered Sun Cleric'),
    ('EX1_536',         'Eaglehorn Bow'),
    ('EX1_165',         'Druid of the Claw'),
    ('DS1_070o',        "Master's Presence"),
    ('EX1_562',         'Onyxia'),
    ('EX1_tk31',        'Mind Controlling'),
    ('EX1_134',         'SI:7 Agent'),
    ('EX1_160t',        'Panther'),
    ('CS2_061',         'Drain Life'),
    ('CS2_012',         'Swipe'),
    ('EX1_366',         'Sword of Justice'),
    ('XXX_003',         'Restore 1'),
    ('EX1_165t1',       'Druid of the Claw'),
    ('DREAM_02',        'Ysera Awakens'),
    ('NEW1_009',        'Healing Totem'),
    ('EX1_371',         'Hand of Protection'),
    ('EX1_045',         'Ancient Watcher'),
    ('EX1_577',         'The Beast'),
    ('TU4f_005',        'Brewmaster'),
    ('TU4f_001',        'Lorewalker Cho'),
    ('XXX_040',         'Hogger'),
    ('CS2_004',         'Power Word: Shield'),
    ('CRED_02',         'Eric Dodds'),
    ('CS2_234',         'Shadow Word: Pain'),
    ('EX1_391',         'Slam'),
    ('GAME_003e',       "Coin's Vengence"),
    ('EX1_310',         'Doomguard'),
    ('DS1_188',         "Gladiator's Longbow"),
    ('EX1_tk34',        'Infernal'),
    ('EX1_345t',        'Shadow of Nothing'),
    ('EX1_407',         'Brawl'),
    ('TU4f_006o',       'Transcendence'),
    ('NEW1_004',        'Vanish'),
    ('EX1_057',         'Ancient Brewmaster'),
    ('EX1_295o',        'Ice Block'),
    ('CS2_200',         'Boulderfist Ogre'),
    ('XXX_017',         'Draw 3 Cards'),
    ('NEW1_010',        "Al'Akir the Windlord"),
    ('EX1_166b',        'Dispel'),
    ('CS2_026',         'Frost Nova'),
    ('EX1_155a',        'Mark of Nature'),
    ('EX1_155ae',       'Mark of Nature'),
    ('CS2_076',         'Assassinate'),
    ('EX1_002',         'The Black Knight'),
    ('XXX_029',         'Opponent Concede'),
    ('EX1_048',         'Spellbreaker'),
    ('CS2_063',         'Corruption'),
    ('CS2_056',         'Life Tap'),
    ('EX1_411e',        'Bloodrage'),
    ('CS2_009e',        'Mark of the Wild'),
    ('CS2_011',         'Savage Roar'),
    ('CS2_105e',        'Heroic Strike'),
    ('TU4a_006',        'Jaina Proudmoore'),
    ('CS2_008',         'Moonfire'),
    ('EX1_015',         'Novice Engineer'),
    ('CS2_007',         'Healing Touch'),
    ('EX1_383',         'Tirion Fordring'),
    ('tt_010',          'Spellbender'),
    ('HERO_05',         'Rexxar'),
    ('EX1_507',         'Murloc Warleader'),
    ('HERO_04',         'Uther Lightbringer'),
    ('EX1_128',         'Conceal'),
    ('EX1_110t',        'Baine Bloodhoof'),
    ('EX1_339',         'Thoughtsteal'),
    ('EX1_587',         'Windspeaker'),
    ('TU4a_004',        'Hogger SMASH!'),
    ('EX1_533',         'Misdirection'),
    ('XXX_021',         'Restore All Health'),
    ('NEW1_032',        'Misha'),
    ('TU4e_003',        'Naga Myrmidon'),
    ('EX1_046e',        'Tempered'),
    ('XXX_008',         'Freeze'),
    ('EX1_522',         'Patient Assassin'),
    ('CS2_023',         'Arcane Intellect'),
    ('NEW1_006',        'Adrenaline Rush'),
    ('NEW1_026',        'Violet Teacher'),
    ('EX1_506',         'Murloc Tidehunter'),
    ('EX1_350',         'Prophet Velen'),
    ('NEW1_036e2',      'Commanding Shout'),
    ('EX1_414',         'Grommash Hellscream'),
    ('CS2_172',         'Bloodfen Raptor'),
    ('EX1_393',         'Amani Berserker'),
    ('TU4e_005',        'Flame Burst'),
    ('EX1_finkle',      'Finkle Einhorn'),
    ('CS2_091',         "Light's Justice"),
    ('XXX_002',         'Damage 5'),
    ('EX1_014t',        'Bananas'),
    ('XXX_009e',        'Empty Enchant'),
    ('tt_004o',         'Cannibalize'),
    ('EX1_251',         'Forked Lightning'),
    ('CS2_182',         'Chillwind Yeti'),
    ('CS2_073e2',       'Cold Blood'),
    ('EX1_409t',        'Heavy Axe'),
    ('EX1_093',         'Defender of Argus'),
    ('EX1_178b',        'Uproot'),
    ('CS2_075',         'Sinister Strike'),
    ('EX1_tk29',        'Devilsaur'),
    ('EX1_016t',        'Skeleton'),
    ('EX1_621',         'Circle of Healing'),
    ('EX1_128e',        'Concealed'),
    ('CS2_034',         'Fireblast'),
    ('EX1_279',         'Pyroblast'),
    ('CS2_tk1',         'Sheep'),
    ('XXX_024',         'Damage Reflector'),
    ('EX1_021',         'Thrallmar Farseer'),
    ('EX1_258e',        'Overloading'),
    ('CS2_103e2',       'Charge'),
    ('EX1_408',         'Mortal Strike'),
    ('EX1_017',         'Jungle Panther'),
    ('EX1_160b',        'Leader of the Pack'),
    ('CS2_188',         'Abusive Sergeant'),
    ('CS2_094',         'Hammer of Wrath'),
    ('EX1_304e',        'Consume'),
    ('EX1_110',         'Cairne Bloodhoof'),
    ('EX1_160a',        'Summon a Panther'),
    ('tt_010a',         'Spellbender'),
    ('XXX_020',         'Damage all but 1'),
    ('EX1_166',         'Keeper of the Grove'),
    ('CS2_029',         'Fireball'),
    ('CS2_122',         'Raid Leader'),
    ('EX1_006',         'Alarm-o-Bot'),
    ('EX1_560',         'Nozdormu'),
    ('EX1_044e',        'Level Up!'),
    ('EX1_586',         'Sea Giant'),
    ('CS2_171',         'Stonetusk Boar'),
    ('EX1_616',         'Mana Wraith'),
    ('TU4e_006',        'Metamorphosis'),
    ('EX1_130',         'Noble Sacrifice'),
    ('EX1_581',         'Sap'),
    ('EX1_584',         'Ancient Mage'),
    ('XXX_023',         'Destroy All Heroes'),
    ('XXX_015',         'Crash'),
    ('XXX_022',         'Free Cards'),
    ('Mekka3',          'Emboldener 3000'),
    ('CS2_173',         'Bluegill Warrior'),
    ('DS1_055',         'Darkscale Healer'),
    ('CS2_063e',        'Corruption'),
    ('HERO_02',         'Thrall'),
    ('NEW1_031',        'Animal Companion'),
    ('XXX_012',         'Bounce'),
    ('CS2_003',         'Mind Vision'),
    ('NEW1_019',        'Knife Juggler'),
    ('CRED_14',         'Yong Woo'),
    ('NEW1_037',        'Master Swordsmith'),
    ('EX1_619',         'Equality'),
    ('HERO_01',         'Garrosh Hellscream'),
    ('EX1_001e',        'Warded'),
    ('CS2_101',         'Reinforce'),
    ('CS2_045',         'Rockbiter Weapon'),
    ('CRED_12',         'Rachelle Davis'),
    ('XXX_009',         'Enchant'),
    ('CS2_104',         'Rampage'),
    ('tt_004',          'Flesheating Ghoul'),
    ('EX1_539',         'Kill Command'),
    ('CS2_181e',        'Full Strength'),
    ('XXX_045',         'Steal Card'),
    ('CS2_051',         'Stoneclaw Totem'),
    ('CS2_092e',        'Blessing of Kings'),
    ('CS2_009',         'Mark of the Wild'),
    ('CS2_102',         'Armor Up!'),
    ('NEW1_024o',       "Greenskin's Command"),
    ('EX1_608',         "Sorcerer's Apprentice"),
    ('DS1_175o',        'Furious Howl'),
    ('CS2_201',         'Core Hound'),
    ('EX1_250',         'Earth Elemental'),
    ('EX1_544',         'Flare'),
    ('CS2_087e',        'Blessing of Might'),
    ('EX1_537',         'Explosive Shot'),
    ('CS2_boar',        'Boar'),
    ('EX1_080o',        'Keeping Secrets'),
    ('TU4d_003',        'Shotgun Blast'),
    ('CS2_022e',        'Polymorph'),
    ('CRED_09',         'Ben Thompson'),
    ('EX1_145o',        'Preparation'),
    ('EX1_366e',        'Justice Served'),
    ('EX1_289',         'Ice Barrier'),
    ('CS2_213',         'Reckless Rocketeer'),
    ('TU4f_004o',       'Legacy of the Emperor'),
    ('TU4e_002',        'Flames of Azzinoth'),
    ('EX1_155be',       'Mark of Nature'),
    ('XXX_001',         'Damage 1'),
    ('CS2_041',         'Ancestral Healing'),
    ('HERO_08',         'Jaina Proudmoore'),
    ('EX1_534',         'Savannah Highmane'),
    ('EX1_573a',        "Demigod's Favor"),
    ('EX1_301',         'Felguard'),
    ('CS2_237',         'Starving Buzzard'),
    ('CS2_124',         'Wolfrider'),
    ('CS2_197',         'Ogre Magi'),
    ('EX1_100',         'Lorewalker Cho'),
    ('EX1_033',         'Windfury Harpy'),
    ('EX1_170',         'Emperor Cobra'),
    ('EX1_010',         'Worgen Infiltrator'),
    ('TU4c_003',        'Barrel'),
    ('EX1_536e',        'Upgraded'),
    ('CRED_11',         'Jay Baxter'),
    ('EX1_023',         'Silvermoon Guardian'),
    ('Mekka1',          'Homing Chicken'),
    ('EX1_390',         'Tauren Warrior'),
    ('TU4c_006e',       'Bananas'),
    ('DS1h_292',        'Steady Shot'),
    ('EX1_317',         'Sense Demons'),
    ('EX1_244',         'Totemic Might'),
    ('EX1_029',         'Leper Gnome'),
    ('EX1_162',         'Dire Wolf Alpha'),
    ('TU4c_001',        'King Mukla'),
    ('EX1_323h',        'Lord Jaraxxus'),
    ('CS2_105',         'Heroic Strike'),
    ('EX1_565o',        'Flametongue'),
    ('EX1_354',         'Lay on Hands'),
    ('CRED_05',         'Kyle Harrison'),
    ('EX1_243',         'Dust Devil'),
    ('EX1_tk28',        'Squirrel'),
    ('CS1_069',         'Fen Creeper'),
    ('EX1_249',         'Baron Geddon'),
    ('CS2_045e',        'Rockbiter Weapon'),
    ('skele21',         'Damaged Golem'),
    ('EX1_062',         'Old Murk-Eye'),
    ('EX1_083',         'Tinkmaster Overspark'),
    ('CS2_187',         'Booty Bay Bodyguard'),
    ('CRED_03',         'Bob Fitch'),
    ('CS1_129e',        'Inner Fire'),
    ('NEW1_017e',       'Full Belly'),
    ('CRED_01',         'Jason Chayes'),
    ('EX1_363',         'Blessing of Wisdom'),
    ('TU4c_006',        'Bananas'),
    ('EX1_044',         'Questing Adventurer'),
    ('EX1_383t',        'Ashbringer'),
    ('EX1_382',         'Aldor Peacekeeper'),
    ('EX1_563',         'Malygos'),
    ('EX1_050',         'Coldlight Oracle'),
    ('EX1_091o',        'Cabal Control'),
    ('EX1_341',         'Lightwell'),
    ('CS2_031',         'Ice Lance'),
    ('EX1_158e',        'Soul of the Forest'),
    ('CS2_037',         'Frost Shock'),
    ('XXX_028',         'Reveal Hand'),
    ('EX1_582',         'Dalaran Mage'),
    ('CRED_08',         'Ben Brode'),
    ('TU4c_008e',       'Might of Mukla'),
    ('CS2_188o',        "'Inspired'"),
    ('EX1_169',         'Innervate'),
    ('CS2_046e',        'Bloodlust'),
    ('EX1_573t',        'Treant'),
    ('EX1_011',         'Voodoo Doctor'),
    ('EX1_001',         'Lightwarden'),
    ('EX1_097',         'Abomination'),
    ('CS2_104e',        'Rampage'),
    ('NEW1_038',        'Gruul'),
    ('EX1_164a',        'Nourish'),
    ('EX1_363e2',       'Blessing of Wisdom'),
    ('EX1_043e',        'Hour of Twilight'),
    ('EX1_160be',       'Leader of the Pack'),
    ('PRO_001a',        'I Am Murloc'),
    ('EX1_606',         'Shield Block'),
    ('EX1_379',         'Repentance'),
    ('NEW1_007a',       'Starfall'),
    ('EX1_246e',        'Hexxed'),
    ('CS2_028',         'Blizzard'),
    ('EX1_004e',        "Elune's Grace"),
    ('DREAM_03',        'Emerald Drake'),
    ('CS2_131',         'Stormwind Knight'),
    ('CS2_082',         'Wicked Knife'),
    ('EX1_059',         'Crazed Alchemist'),
    ('CS2_179',         "Sen'jin Shieldmasta"),
    ('EX1_091',         'Cabal Shadow Priest'),
    ('EX1_335',         'Lightspawn'),
    ('EX1_025t',        'Mechanical Dragonling'),
    ('EX1_620',         'Molten Giant'),
    ('EX1_573',         'Cenarius'),
    ('CS2_169',         'Young Dragonhawk'),
    ('EX1_080',         'Secretkeeper'),
    ('EX1_028',         'Stranglethorn Tiger'),
    ('CS2_120',         'River Crocolisk'),
    ('EX1_312',         'Twisting Nether'),
    ('EX1_570',         'Bite'),
    ('EX1_066',         'Acidic Swamp Ooze'),
    ('CS2_093',         'Consecration'),
    ('EX1_604',         'Frothing Berserker'),
    ('EX1_613e',        "VanCleef's Vengeance"),
    ('CS2_077',         'Sprint'),
    ('NEW1_007b',       'Starfall'),
    ('EX1_396',         "Mogu'shan Warden"),
    ('EX1_274e',        'Raw Power!'),
    ('EX1_578',         'Savagery'),
    ('EX1_334e',        'Dark Command'),
    ('EX1_tk33',        'INFERNO!'),
    ('NEW1_023',        'Faerie Dragon'),
    ('EX1_506a',        'Murloc Scout'),
    ('DS1_185',         'Arcane Shot'),
    ('hexfrog',         'Frog'),
    ('EX1_049',         'Youthful Brewmaster'),
    ('EX1_178',         'Ancient of War'),
    ('EX1_084',         'Warsong Commander'),
    ('DREAM_05e',       'Nightmare'),
    ('NEW1_033',        'Leokk'),
    ('DS1_183',         'Multi-Shot'),
    ('EX1_319',         'Flame Imp'),
    ('NEW1_008b',       'Ancient Secrets'),
    ('EX1_019e',        "Cleric's Blessing"),
    ('EX1_259',         'Lightning Storm'),
    ('TU4c_005',        'Hidden Gnome'),
    ('EX1_625t',        'Mind Spike'),
    ('EX1_573ae',       "Demigod's Favor"),
    ('EX1_275',         'Cone of Cold'),
    ('XXX_014',         'Mill 10'),
    ('EX1_084e',        'Charge'),
    ('HERO_09',         'Anduin Wrynn'),
    ('EX1_005',         'Big Game Hunter'),
    ('CS2_203',         'Ironbeak Owl'),
    ('EX1_355',         'Blessed Champion'),
    ('EX1_130a',        'Defender'),
    ('CS2_226o',        'Commanding'),
    ('EX1_398',         'Arathi Weaponsmith'),
    ('TU4c_004',        'Stomp'),
    ('GAME_003',        "Coin's Vengeance"),
    ('CS2_119',         'Oasis Snapjaw'),
    ('EX1_411e2',       'Needs Sharpening'),
    ('EX1_154a',        'Wrath'),
    ('EX1_595',         'Cult Master'),
    ('CS2_065',         'Voidwalker'),
    ('EX1_112',         'Gelbin Mekkatorque'),
    ('EX1_604o',        'Berserk'),
    ('EX1_008',         'Argent Squire'),
    ('EX1_244e',        'Totemic Might'),
    ('EX1_012',         'Bloodmage Thalnos'),
    ('DS1_178',         'Tundra Rhino'),
    ('EX1_363e',        'Blessing of Wisdom'),
    ('EX1_315',         'Summoning Portal'),
    ('EX1_133',         "Perdition's Blade"),
    ('TU4e_002t',       'Flame of Azzinoth'),
    ('CS1_112',         'Holy Nova'),
    ('CS2_053',         'Far Sight'),
    ('CS2_122e',        'Enhanced'),
    ('EX1_614',         'Illidan Stormrage'),
    ('TU4f_002',        'Pandaren Scout'),
    ('EX1_009',         'Angry Chicken'),
    ('EX1_154b',        'Wrath'),
    ('CS2_038',         'Ancestral Spirit'),
    ('EX1_058',         'Sunfury Protector'),
    ('EX1_360e',        'Humility'),
    ('EX1_165t2',       'Druid of the Claw'),
    ('EX1_287',         'Counterspell'),
    ('DS1_070',         'Houndmaster'),
    ('EX1_400',         'Whirlwind'),
    ('CS2_004e',        'Power Word: Shield'),
    ('CS2_146',         'Southsea Deckhand'),
    ('EX1_603',         'Cruel Taskmaster'),
    ('CS2_052',         'Wrath of Air Totem'),
    ('CS2_103',         'Charge'),
    ('EX1_105',         'Mountain Giant'),
    ('NEW1_041',        'Stampeding Kodo'),
    ('CS2_017',         'Shapeshift'),
    ('CS2_127',         'Silverback Patriarch'),
    ('EX1_316',         'Power Overwhelming'),
    ('CS2_097',         'Truesilver Champion'),
    ('EX1_tk9',         'Treant'),
    ('NEW1_018e',       'Treasure Crazed'),
    ('DS1_233',         'Mind Blast'),
    ('EX1_103e',        'Mrghlglhal'),
    ('XXX_042',         'Hand to Deck'),
    ('EX1_155b',        'Mark of Nature'),
    ('NEW1_037e',       'Equipped'),
    ('EX1_624',         'Holy Fire'),
    ('NEW1_025e',       'Bolstered'),
    ('GAME_005',        'The Coin'),
    ('CS2_073',         'Cold Blood'),
    ('CS2_121',         'Frostwolf Grunt'),
    ('CS2_062',         'Hellfire'),
    ('EX1_409e',        'Upgraded'),
    ('NEW1_014',        'Master of Disguise'),
    ('Mekka2',          'Repair Bot'),
    ('CS2_005',         'Claw'),
    ('EX1_096',         'Loot Hoarder'),
    ('CS2_232',         'Ironbark Protector'),
    ('CS2_189',         'Elven Archer'),
    ('NEW1_016',        "Captain's Parrot"),
    ('EX1_531e',        'Well Fed'),
    ('CS2_196',         'Razorfen Hunter'),
    ('CS2_112',         'Arcanite Reaper'),
    ('TU4c_002',        'Barrel Toss'),
    ('XXX_030',         'Opponent Disconnect'),
    ('EX1_531',         'Scavenging Hyena'),
    ('EX1_323w',        'Blood Fury'),
    ('EX1_571',         'Force of Nature'),
    ('EX1_004',         'Young Priestess'),
    ('EX1_124',         'Eviscerate'),
    ('EX1_103',         'Coldlight Seer'),
    ('EX1_565',         'Flametongue Totem'),
    ('CS2_072',         'Backstab'),
    ('CS2_087',         'Blessing of Might'),
    ('DS1_184',         'Tracking'),
    ('EX1_102',         'Demolisher'),
    ('CS2_024',         'Frostbolt'),
    ('TU4f_003',        'Shado-Pan Monk'),
    ('TU4c_007',        "Mukla's Big Brother"),
    ('CS2_222',         'Stormwind Champion'),
    ('CS2_046',         'Bloodlust'),
    ('EX1_320',         'Bane of Doom'),
    ('EX1_126',         'Betrayal'),
    ('XXX_005',         'Destroy'),
    ('NEW1_011',        "Kor'kron Elite"),
    ('XXX_007',         'Enable for Attack'),
    ('PRO_001b',        'Rogues Do It...'),
    ('EX1_625t2',       'Mind Shatter'),
    ('EX1_384',         'Avenging Wrath'),
    ('CS2_108',         'Execute'),
    ('NEW1_003',        'Sacrificial Pact'),
    ('CS2_117',         'Earthen Ring Farseer'),
    ('TU4f_006',        'Transcendence'),
    ('CS2_074e',        'Deadly Poison'),
    ('EX1_398t',        'Battle Axe'),
    ('CS1_130',         'Holy Smite'),
    ('NEW1_025',        'Bloodsail Corsair'),
    ('CS2_221e',        'Sharp!'),
    ('EX1_161',         'Naturalize'),
    ('EX1_410',         'Shield Slam'),
    ('CS2_022',         'Polymorph'),
    ('TU4e_001',        'Illidan Stormrage'),
    ('NEW1_012',        'Mana Wyrm'),
    ('Mekka3e',         'Emboldened!'),
    ('Mekka4e',         'Transformed'),
    ('NEW1_008',        'Ancient of Lore'),
    ('CS2_017o',        'Claws'),
    ('EX1_162o',        'Strength of the Pack'),
    ('CS2_141',         'Ironforge Rifleman'),
    ('EX1_564',         'Faceless Manipulator'),
    ('EX1_603e',        'Whipped Into Shape'),
    ('CS2_101t',        'Silver Hand Recruit'),
    ('EX1_178a',        'Rooted'),
    ('CRED_10',         'Michael Schweitzer'),
    ('EX1_509e',        'Blarghghl'),
    ('CS2_049',         'Totemic Call'),
    ('EX1_612o',        'Power of the Kirin Tor'),
    ('EX1_558',         'Harrison Jones'),
    ('EX1_573b',        "Shan'do's Lesson"),
    ('CRED_15',         'Andy Brock'),
    ('EX1_554',         'Snake Trap'),
    ('NEW1_040',        'Hogger'),
    ('EX1_165a',        'Cat Form'),
    ('EX1_248',         'Feral Spirit'),
    ('EX1_238',         'Lightning Bolt'),
    ('CS2_114',         'Cleave'),
    ('TU4f_004',        'Legacy of the Emperor'),
    ('EX1_277',         'Arcane Missiles'),
    ('EX1_155',         'Mark of Nature'),
    ('EX1_020',         'Scarlet Crusader'),
    ('HERO_03',         'Valeera Sanguinar'),
    ('EX1_258',         'Unbound Elemental'),
    ('CS2_106',         'Fiery War Axe'),
    ('XXX_010',         'Silence - debug'),
    ('EX1_612',         'Kirin Tor Mage'),
    ('EX1_360',         'Humility'),
    ('EX1_131t',        'Defias Bandit'),
    ('CS2_236e',        'Divine Spirit'),
    ('EX1_509',         'Murloc Tidecaller'),
    ('NEW1_036e',       'Commanding Shout'),
    ('EX1_241',         'Lava Burst'),
    ('EX1_619e',        'Equality'),
    ('CS2_083e',        'Sharpened'),
    ('CS2_084',         "Hunter's Mark"),
    ('EX1_549',         'Bestial Wrath'),
    ('EX1_032',         'Sunwalker'),
    ('EX1_534t',        'Hyena'),
    ('CS2_080',         "Assassin's Blade"),
    ('CS2_226',         'Frostwolf Warlord'),
    ('CS2_181',         'Injured Blademaster'),
    ('EX1_556',         'Harvest Golem'),
    ('EX1_402',         'Armorsmith'),
    ('EX1_334',         'Shadow Madness'),
    ('CS2_231',         'Wisp'),
    ('CS2_033',         'Water Elemental'),
    ('GAME_001',        'Luck of the Coin'),
    ('EX1_590e',        "Shadows of M'uru"),
    ('EX1_082',         'Mad Bomber'),
    ('XXX_018',         'Destroy All Minions'),
    ('EX1_025',         'Dragonling Mechanic'),
    ('TU4d_002',        'Crazed Hunter'),
    ('EX1_594',         'Vaporize'),
    ('EX1_294',         'Mirror Entity'),
    ('GAME_005e',       'The Coin'),
    ('NEW1_018',        'Bloodsail Raider'),
    ('CRED_07',         'Zwick'),
    ('HERO_07',         "Gul'dan"),
    ('CS2_089',         'Holy Light'),
    ('EX1_043',         'Twilight Drake'),
    ('EX1_067',         'Argent Commander'),
    ('CS2_186',         'War Golem'),
    ('TU4d_001',        'Hemet Nesingwary'),
    ('EX1_076',         'Pint-Sized Summoner'),
    ('CRED_04',         'Steven Gabriel'),
    ('CS2_059',         'Blood Imp'),
    ('NEW1_036',        'Commanding Shout'),
    ('XXX_043',         'Mill 30'),
    ('EX1_623e',        'Infusion'),
    ('CS2_084e',        "Hunter's Mark"),
    ('DREAM_01',        'Laughing Sister'),
    ('XXX_039',         'Become Hogger'),
    ('EX1_613',         'Edwin VanCleef'),
    ('EX1_131',         'Defias Ringleader'),
    ('PRO_001at',       'Murloc'),
    ('EX1_158t',        'Treant'),
    ('TU4a_003',        'Gnoll'),
    ('EX1_136',         'Redemption'),
    ('GAME_004',        'AFK'),
    ('EX1_059e',        'Experiments!'),
    ('EX1_304',         'Void Terror'),
    ('EX1_609',         'Snipe'),
    ('CS2_235',         'Northshire Cleric'),
    ('EX1_625',         'Shadowform'),
    ('CRED_06',         'Derek Sakamoto'),
    ('CS2_038e',        'Ancestral Spirit'),
    ('EX1_409',         'Upgrade!'),
    ('CS2_083b',        'Dagger Mastery'),
    ('EX1_596',         'Demonfire'),
    ('EX1_362',         'Argent Protector'),
    ('CS1h_001',        'Lesser Heal'),
    ('TU4a_002',        'Riverpaw Gnoll'),
    ('CS2_005o',        'Claw'),
    ('EX1_543',         'King Krush'),
    ('XXX_016',         'Snake Ball'),
    ('EX1_583',         'Priestess of Elune'),
    ('skele11',         'Skeleton'),
    ('NEW1_027e',       'Yarrr!'),
    ('CS2_042',         'Fire Elemental'),
    ('EX1_412',         'Raging Worgen'),
    ('XXX_041',         'Destory Hero Power'),
    ('TU4c_008',        'Will of Mukla'),
    ('CS2_222o',        'Might of Stormwind'),
    ('XXX_022e',        'Free Cards'),
    ('EX1_tk11',        'Spirit Wolf'),
    ('EX1_590',         'Blood Knight'),
    ('CS2_057',         'Shadow Bolt'),
    ('EX1_626',         'Mass Dispel'),
    ('EX1_173',         'Starfire'),
    ('GAME_002',        'Avatar of the Coin'),
    ('EX1_278',         'Shiv'),
    ('EX1_144',         'Shadowstep'),
    ('EX1_283',         'Frost Elemental'),
    ('EX1_095',         'Gadgetzan Auctioneer'),
    ('CS2_050',         'Searing Totem'),
    ('EX1_316e',        'Power Overwhelming'),
    ('CS1_129',         'Inner Fire'),
    ('NEW1_029',        'Millhouse Manastorm'),
    ('EX1_345',         'Mindgames'),
    ('CS2_125',         'Ironfur Grizzly'),
    ('DS1_178e',        'Charge'),
    ('EX1_284',         'Azure Drake'),
    ('EX1_538',         'Unleash the Hounds'),
    ('CS2_150',         'Stormpike Commando'),
    ('EX1_567',         'Doomhammer'),
    ('NEW1_026t',       'Violet Apprentice'),
    ('CS2_227',         'Venture Co. Mercenary'),
    ('EX1_587e',        'Windfury'),
    ('EX1_129',         'Fan of Knives'),
    ('EX1_572',         'Ysera'),
    ('EX1_508',         'Grimscale Oracle'),
    ('EX1_614t',        'Flame of Azzinoth'),
    ('EX1_382e',        'Stand Down!'),
    ('CS1_042',         'Goldshire Footman'),
    ('EX1_365',         'Holy Wrath'),
    ('EX1_611e',        'Trapped'),
    ('EX1_313',         'Pit Lord'),
    ('CS2_092',         'Blessing of Kings'),
    ('XXX_019',         'Molasses'),
    ('EX1_323',         'Lord Jaraxxus'),
    ('CRED_17',         'Rob Pardo'),
    ('EX1_597',         'Imp Master'),
    ('NEW1_005',        'Kidnapper'),
    ('EX1_055o',        'Empowered'),
    ('EX1_164b',        'Nourish'),
    ('EX1_137',         'Headcrack'),
    ('NEW1_024',        'Captain Greenskin'),
    ('CS2_073e',        'Cold Blood'),
    ('TU4a_001',        'Hogger'),
    ('EX1_561',         'Alexstrasza'),
    ('NEW1_021',        'Doomsayer'),
    ('EX1_116',         'Leeroy Jenkins'),
    ('EX1_165b',        'Bear Form'),
    ('NEW1_008a',       'Ancient Teachings'),
    ('CS1_113e',        'Mind Control'),
    ('EX1_007',         'Acolyte of Pain'),
    ('CS2_233',         'Blade Flurry'),
    ('EX1_379e',        'Repentance'),
    ('NEW1_040t',       'Gnoll'),
    ('EX1_584e',        'Teachings of the Kirin Tor'),
    ('XXX_027',         'Server Crash'),
    ('PRO_001',         'Elite Tauren Chieftain'),
    ('EX1_622',         'Shadow Word: Death'),
    ('HERO_06',         'Malfurion Stormrage'),
    ('NEW1_034',        'Huffer'),
    ('EX1_303',         'Shadowflame'),
    ('EX1_317t',        'Worthless Imp'),
    ('CS2_027',         'Mirror Image'),
    ('EX1_617',         'Deadly Shot'),
    ('XXX_011',         'Exhaust'),
    ('NEW1_030',        'Deathwing'),
    ('EX1_538t',        'Hound'),
    ('EX1_014',         'King Mukla'),
    ('CS2_155',         'Archmage'),
    ('EX1_570e',        'Bite'),
    ('CS2_011o',        'Savage Roar'),
    ('TU4e_007',        'Dual Warglaives'),
    ('NEW1_022',        'Dread Corsair'),
    ('EX1_166a',        'Moonfire'),
    ('EX1_306',         'Succubus'),
    ('EX1_399',         'Gurubashi Berserker'),
    ('EX1_349',         'Divine Favor'),
    ('CRED_16',         'Hamilton Chu'),
    ('XXX_026',         'Enable Emotes'),
    ('EX1_093e',        'Hand of Argus'),
    ('NEW1_027',        'Southsea Captain'),
    ('EX1_178be',       'Uprooted'),
    ('EX1_561e',        "Alexstrasza's Fire"),
    ('EX1_392',         'Battle Rage'),
    ('CRED_13',         'Brian Schwab'),
    ('CS2_013',         'Wild Growth'),
    ('CS2_025',         'Arcane Explosion'),
    ('EX1_014te',       'Bananas'),
    ('EX1_089',         'Arcane Golem'),
    ('EX1_593',         'Nightblade'),
    ('EX1_355e',        "Templar's Verdict"),
    ('EX1_245',         'Earth Shock'),
    ('XXX_044',         'Hand Swapper Minion'),
    ('CS2_039',         'Windfury'),
    ('EX1_046',         'Dark Iron Dwarf'),
    ('TU4f_007',        'Crazy Monkey'),
    ('EX1_160',         'Power of the Wild'),
    ('EX1_598',         'Imp'),
    ('EX1_178ae',       'Rooted'),
    ('CS2_013t',        'Excess Mana'),
    ('PRO_001c',        'Power of the Horde'),
    ('EX1_607',         'Inner Rage'),
    ('CS2_146o',        'Sharpened'),
    ('CS2_088',         'Guardian of Kings'),
    ('EX1_298',         'Ragnaros the Firelord'),
    ('CS2_041e',        'Ancestral Infusion'),
    ('EX1_332',         'Silence'),
    ('DREAM_05',        'Nightmare'),
    ('EX1_596e',        'Demonfire'),
    ('EX1_161o',        'Demoralizing Roar'),
    ('TU4b_001',        'Millhouse Manastorm'),
    ('EX1_246',         'Hex'),
    ('CS2_161',         'Ravenholdt Assassin'),
    ('TU4a_005',        'Massive Gnoll'),
    ('NEW1_007',        'Starfall'),
    ('TU4e_004',        'Warglaive of Azzinoth'),
    ('CS2_152',         'Squire'),
    ('CS2_053e',        'Far Sight'),
    ('EX1_607e',        'Inner Rage'),
    ('EX1_623',         'Temple Enforcer'),
    ('DS1_175',         'Timber Wolf'),
    ('EX1_164',         'Nourish'),
    ('EX1_591',         'Auchenai Soulpriest'),
    ('CS2_074',         'Deadly Poison'),
    ('XXX_006',         'Break Weapon'),
    ('CS2_226e',        'Frostwolf Banner'),
    ('EX1_247',         'Stormforged Axe'),
    ('EX1_059e2',       'Experiments!'),
    ('NEW1_029t',       'Kill Millhouse!'),
    ('CS2_118',         'Magma Rager'),
]

_id_to_card = dict(_cards)

def get_by_id(cardid):
    card = _id_to_card.get(cardid, None)
    if card is None:
        raise CardNotFound('Could not find card with id {0}'.format(cardid))
    return card
